### ISSUE TITLE
师傅下午好呀

### ISSUE THREAD

**Issue by bigblackhat** [nu0l/iak-ARL#1]
师傅您好，今天下午我拜读了您写的ARL弱口令检测工具，代码写的很好，我计划参考其检测逻辑，写入我的工具--[oFx](https://github.com/bigblackhat/oFx)，并将您的项目纳入致谢清单，感谢您对开源世界作出的贡献，祝好！

**Comment by nu0l** [comment]
师傅，你好。
非常感谢得到您的认可。
pass：很巧，我也在刚刚使用了您的oFx，我似乎发现了一个小问题，您似乎在开发中，忘记删除fofa-api的信息……








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nu0l/iak-ARL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月23日(星期一) 下午3:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[nu0l/iak-ARL] 师傅下午好呀 (#1)





 
师傅您好，今天下午我拜读了您写的ARL弱口令检测工具，代码写的很好，我计划参考其检测逻辑，写入我的工具--oFx，并将您的项目纳入致谢清单，感谢您对开源世界作出的贡献，祝好！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bigblackhat** [comment]
哈哈你太可爱了，感谢提醒，悄悄告诉你，我是故意的，嘘.....
